services:
#    jj_image.example:
#        class: JJ\ImageBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

# jj_image.form.ckeditor:
#         class: JJ\ImageBundle\Form\CkeditorType
#         tags:
#           - { name: form.type, alias: ckeditor }
