<?php

namespace JJ\ImageBundle\Repository;

/**
 * DisqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DisqueRepository extends \Doctrine\ORM\EntityRepository
{
}
